services:
  - type: web
    name: legalize-site
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legalize-site-postgres
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: legalize_site.settings.production
      - key: PYTHON_VERSION
        value: 3.12.6

databases:
  - name: legalize-site-postgres
    databaseName: legalize_site
    user: legalize_site
